### ISSUE TITLE
Key shortcut conflict with bracket-matcher

### ISSUE THREAD

**Issue by berdario** [jonspalding/lisp-paredit#11]
I'm not sure when bracket-matcher has been added to the default atom installation, but now the `ctrl-alt-.` shortcut for slurp-forward conflicts with it, and bracket-matcher takes precedence.

In my case, I worked around the issue with [this keymap](https://github.com/berdario/dotfiles/commit/f26a7e9534559c321b7a6a034aeb79dc129e1e26)

**Comment by jonspalding** [comment]
Thanks, I'll look at changing the keymap.

**Comment by neil-lindquist** [comment]
This appears that this was fixed but a patch for a similar issue.
