### ISSUE TITLE
Strict mode should not apply to bracket in string

### ISSUE THREAD

**Issue by tony612** [jonspalding/lisp-paredit#12]
I want to type this code:

``` scheme
(define (print-point p)
  (newline)
  (display "(")
  ; ...
  (display ")"))
```

But after I type the left parenthesis in first string, I can't type the right parenthesis in the last string:

`````` scheme
```scheme
(define (print-point p)
  (newline)
  (display "(")
  ; ...
  (display "")) ; I can't type `)` in the string
``````

Is this because of strict config?

**Comment by jonspalding** [comment]
Yeah this is a bug. I'll take a look.

**Comment by mauricioszabo** [comment]
Any news on this? It's kinda old, and it's kinda painful...

**Comment by neil-lindquist** [comment]
I've just push the fix to this to the master branch and will include it in the next release.
