### ISSUE TITLE
Multiline string indentation is not preserved

### ISSUE THREAD

**Issue by jasongilman** [jonspalding/lisp-paredit#14]
lisp-paredit is currently using 0.2.11 of paredit.js. multiline string indentation is not being preserved when reindenting a block of code. I filed this [issue against paredit.js](https://github.com/rksm/paredit.js/issues/8). This has been fixed in version 0.2.12. This issue should be fixable by upgrading paredit.js.

**Comment by jonspalding** [comment]
Released in 0.5.2
