### ISSUE TITLE
Option to extend the supported grammar list via config?

### ISSUE THREAD

**Issue by dead-claudia** [jonspalding/lisp-paredit#17]
I'm looking at there's quite a few lesser-known Lisps (and other s-expression-based languages) that will likely never be popular enough to be popular here, like [Sibilant](https://sibilantjs.info/), and some that might, like [LFE (Lisp Flavoured Erlang)](http://lfe.io/), somewhat notable in Erlang circles. I've also occasionally contributed to [ESLisp](https://github.com/anko/eslisp), an experiment of what JavaScript would be like if it used s-expressions instead of curly braces (the rest of the semantics are nearly identical). It would be nice to have a config option to enable support for this in other grammars beyond the stock set.

**Comment by neil-lindquist** [comment]
I've implemented this in the master branch, and will include it in the next release.
