### ISSUE TITLE
Scheme indentation incorrect

### ISSUE THREAD

**Issue by ghost** [jonspalding/lisp-paredit#21]
For example, indenting this:

``` scheme
(lambda ()
  (display "foo"))
```

results in:

``` scheme
(lambda ()
        (display "foo"))
```

**Comment by rgdelato** [comment]
You can fix this by adding `lambda` to your indentation forms in the package settings.

**Comment by neil-lindquist** [comment]
I added a note to the readme, which will hopefully prevent this from being a sticking point in the future.
