### ISSUE TITLE
shrink selection is missing

### ISSUE THREAD

**Issue by yogthos** [jonspalding/lisp-paredit#24]
there's `ctrl-w expand-selection` to expand selection, but I don't see a way to shrink selection to previous state

**Comment by LukeDefeo** [comment]
+1

**Comment by kentywang** [comment]
@yogthos @LukeDefeo I've implemented this feature on [my fork](https://github.com/kentywang/lisp-paredit/tree/contract-selection). The default shortcut for `contract-selection` is `ctrl-alt-space` to match paredit-js.

**Comment by yogthos** [comment]
👍

**Comment by jonspalding** [comment]
Released in 0.6.0.
