### ISSUE TITLE
splice-backwards and forwards doesn't appear to do anything

### ISSUE THREAD

**Issue by DireMunchkin** [jonspalding/lisp-paredit#3]
Am I correct in assuming this is supposed to implement splice with forwards and backwards kill sexpr from paredit.js? If so, it doesn't appear to work as intended, it doesn't appear to change my source files at all. I used keymap-resolver to verify that the default keybindings where pointing to the right actions, but if they are executing they don't appear to be changing the source at all.

**Comment by jonspalding** [comment]
Hi, 

Sorry for the late reply. What OS/Atom/lisp-paredit versions are you running? I'll try to reproduce.

Also would be good to have an example source file.

Thanks,

**Comment by DireMunchkin** [comment]
Hmm, I actually can't reproduce the error on paredit 0.4.0, so I guess you can consider this closed. :)
