### ISSUE TITLE
Deprecated selector in `lisp-paredit/styles/lisp-paredit.atom-text-editor.less`

### ISSUE THREAD

**Issue by vincentjames501** [jonspalding/lisp-paredit#30]
In `lisp-paredit/styles/lisp-paredit.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .lisp-syntax-error .region` => `atom-text-editor.editor .lisp-syntax-error .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Alhadis** [comment]
Will be fixed by #29, it's just a matter of when/if @jonspalding merges it. :)

**Comment by jonspalding** [comment]
Released in 0.5.5.
