### ISSUE TITLE
Auto indent not working after barfing and slurping

### ISSUE THREAD

**Issue by krzysztofpniak** [jonspalding/lisp-paredit#8]
After barfing and slurping autoindentation does not work(at least on windows). It should work like in this video: https://www.youtube.com/watch?v=D6h5dFyyUX0 1:00 - 1:10

**Comment by krzysztofpniak** [comment]
Hello,
 when it will be available on atom packages?
Kind regards
Krzysztof

-----Wiadomość oryginalna-----
Od: "Jon Spalding" notifications@github.com
Wysłano: ‎2015-‎10-‎22 15:06
Do: "jonspalding/lisp-paredit" lisp-paredit@noreply.github.com
DW: "krzysztofpniak" krzysztof.pniak@gmail.com
Temat: Re: [lisp-paredit] Auto indent not working after barfing and slurping(#8)

Closed #8 via 3a890ef.

**Comment by jonspalding** [comment]
Now available in  0.5.0. Thanks for the feedback.

**Comment by krzysztofpniak** [comment]
Barf forward works well, Slurp forward (ctrl + alt + .) does not work. Nothing happens.

Thanks for rework.

**Comment by jonspalding** [comment]
Have you got an example?

**Comment by krzysztofpniak** [comment]
(if (= 1 )
  (println "asda")
  (println "asdad")
  (println "asdasd"))

In the example above I can move last bracket backward, but I cannot move it forward.

2015-10-22 20:51 GMT+02:00 Jon Spalding notifications@github.com:

**Comment by jonspalding** [comment]
Works ok on Mac, need to test it on Windows.

**Comment by neil-lindquist** [comment]
This does not appear to be an issue any more.  Please reopen this issue if I'm misunderstanding the problem.
