### ISSUE TITLE
Wrong indentation after wrap and move inner expression to new line

### ISSUE THREAD

**Issue by krzysztofpniak** [jonspalding/lisp-paredit#9]
It is visible in this video:
https://www.youtube.com/watch?v=IIly4MjyAbc

I have 0.5.0 version installed, I also restarted atom.

**Comment by jonspalding** [comment]
Not sure I can see anything wrong here, after a new line is inserted it will only apply auto indent to the new line. 

What would you expect to happen?

**Comment by krzysztofpniak** [comment]
here you can see better what is going on. https://www.youtube.com/watch?v=uXVR2-2XqHA
I will check it on Mac later.

**Comment by neil-lindquist** [comment]
The video links are broken, so I'm going to close this issue unless someone has information on what this issue is.
